# Generated by Django 5.2.1 on 2026-03-01 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='tamaño_etiqueta',
            field=models.CharField(choices=[('chica', 'Chica'), ('mediana', 'Mediana'), ('grande', 'Grande')], default='mediana', max_length=20),
        ),
    ]
