# Generated by Django 5.2.1 on 2026-03-02 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0003_producto_tamaño_etiqueta'),
        ('tienda_temp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='firma_unica',
            field=models.CharField(blank=True, help_text='Huella digital interna para evitar duplicados', max_length=600, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='precio_docena',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Opcional. Solo si el dueño decide manejar precio por docena.', max_digits=10, null=True),
        ),
        migrations.AddConstraint(
            model_name='producto',
            constraint=models.UniqueConstraint(fields=('firma_unica',), name='unique_producto_por_firma'),
        ),
    ]
