# Generated by Django 5.2.1 on 2026-03-07 08:27

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0004_producto_firma_unica_alter_producto_precio_docena_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='embedding',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), blank=True, null=True, size=768),
        ),
    ]
