# Generated by Django 5.2.1 on 2026-03-07 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0005_producto_embedding'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='embedding',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
