# Generated by Django 5.2.1 on 2026-03-09 06:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0006_alter_producto_embedding'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producto',
            old_name='tamaño_etiqueta',
            new_name='tamano_etiqueta',
        ),
    ]
