# Generated by Django 5.2.1 on 2026-03-14 21:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0007_rename_tamaño_etiqueta_producto_tamano_etiqueta'),
        ('sucursales', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ubicacion',
            name='activa',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='ubicacion',
            name='sucursal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ubicaciones', to='sucursales.sucursal'),
        ),
        migrations.AddField(
            model_name='ubicacion',
            name='tipo',
            field=models.CharField(choices=[('piso', 'Piso de Venta'), ('bodega', 'Bodega Interna'), ('global', 'Global / Almacén Central')], default='global', max_length=20),
        ),
        migrations.AlterField(
            model_name='ubicacion',
            name='nombre',
            field=models.CharField(max_length=50),
        ),
    ]
