# Generated by Django 5.2.1 on 2026-03-23 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0008_ubicacion_activa_ubicacion_sucursal_ubicacion_tipo_and_more'),
        ('inventario', '0009_auto_20260323_1604'),
    ]

    operations = [
    ]
