# Generated by Django 5.2.1 on 2026-03-24 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0008_ubicacion_activa_ubicacion_sucursal_ubicacion_tipo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='embedding',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
