# Generated by Django 5.2.1 on 2026-04-09 05:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0011_alter_producto_embedding'),
        ('tienda_temp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='activo',
            field=models.BooleanField(default=True, help_text='False = producto desactivado, no aparece en inventario ni POS'),
        ),
        migrations.AddField(
            model_name='producto',
            name='desactivado_por',
            field=models.ForeignKey(blank=True, help_text='Empleado que desactivó el producto — se llena automáticamente', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='productos_desactivados', to='tienda_temp.empleado'),
        ),
        migrations.AddField(
            model_name='producto',
            name='fecha_desactivacion',
            field=models.DateTimeField(blank=True, help_text='Fecha en que fue desactivado — se llena automáticamente', null=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='motivo_desactivacion',
            field=models.CharField(blank=True, help_text='Razón por la que se desactivó — lo escribe el usuario en el modal', max_length=300, null=True),
        ),
    ]
