# Generated by Django 5.2.1 on 2026-04-12 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0012_producto_activo_producto_desactivado_por_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='precio_docena',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Opcional. Solo si el dueño decide manejar precio por docena.', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='precio_mayoreo',
            field=models.DecimalField(decimal_places=1, max_digits=10),
        ),
        migrations.AlterField(
            model_name='producto',
            name='precio_menudeo',
            field=models.DecimalField(decimal_places=1, max_digits=10),
        ),
    ]
