# Generated by Django 5.2.1 on 2026-04-12 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0013_alter_producto_precio_docena_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='costo',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Costo del producto — solo visible para el dueño', max_digits=10, null=True),
        ),
    ]
