# Generated by Django 5.2.1 on 2026-05-07 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0015_replace_embedding_with_phash'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='foto_thumbnail',
            field=models.ImageField(blank=True, help_text='Versión pequeña auto-generada para listas y cards. No editar manualmente.', null=True, upload_to='productos/thumbs/'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='descripcion',
            field=models.TextField(blank=True),
        ),
    ]
