# Generated by Django 5.2.1 on 2026-05-20 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0017_codigo_barras_no_unique'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='foto_thumbnail',
        ),
    ]
