# Generated by Django 5.2.1 on 2026-03-19 03:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sucursales', '0001_initial'),
        ('ventas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='caja',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sucursales.caja'),
        ),
    ]
