# Generated by Django 5.2.1 on 2026-03-23 03:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sucursales', '0001_initial'),
        ('tienda_temp', '0001_initial'),
        ('ventas', '0002_venta_caja'),
    ]

    operations = [
        migrations.CreateModel(
            name='CorteCaja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('total_general', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_por_dueno', models.JSONField()),
                ('caja', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sucursales.caja')),
                ('empleado', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tienda_temp.empleado')),
            ],
        ),
    ]
