# Generated by Django 5.2.1 on 2026-04-09 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0003_cortecaja'),
    ]

    operations = [
        migrations.AddField(
            model_name='ventadetalle',
            name='atributos_snapshot',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ventadetalle',
            name='nombre_snapshot',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
