# Generated by Django 5.2.1 on 2026-04-09 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0004_ventadetalle_atributos_snapshot_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cortecaja',
            name='ventas',
            field=models.ManyToManyField(blank=True, related_name='cortes', to='ventas.venta'),
        ),
    ]
