# Generated by Django 5.2.1 on 2026-04-11 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0005_cortecaja_ventas'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='caja_nombre',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
