# Generated by Django 5.2.1 on 2026-04-11 06:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sucursales', '0001_initial'),
        ('ventas', '0006_venta_caja_nombre'),
    ]

    operations = [
        migrations.AddField(
            model_name='cortecaja',
            name='caja_nombre',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='cortecaja',
            name='caja',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sucursales.caja'),
        ),
    ]
