# Generated by Django 5.2.1 on 2026-04-22 18:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0015_replace_embedding_with_phash'),
        ('ventas', '0007_cortecaja_caja_nombre_alter_cortecaja_caja'),
    ]

    operations = [
        migrations.CreateModel(
            name='Promocion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('descripcion', models.TextField(blank=True)),
                ('activo', models.BooleanField(default=True)),
                ('tipo_condicion', models.CharField(choices=[('categoria', 'Categoría de producto'), ('monto', 'Monto mínimo de compra')], max_length=20)),
                ('monto_minimo', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('tipo_resultado', models.CharField(choices=[('regalo_fijo', 'Producto de regalo fijo'), ('regalo_variante', 'El cliente escoge de una categoría')], max_length=20)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('categoria_disparadora', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='promociones_disparadoras', to='inventario.categoria')),
                ('categoria_regalo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='promociones_categoria_regalo', to='inventario.categoria')),
                ('producto_regalo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='promociones_como_regalo', to='inventario.producto')),
            ],
            options={
                'ordering': ['-activo', 'nombre'],
            },
        ),
    ]
