# Generated by Django 5.2.1 on 2026-04-22 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0008_add_promocion'),
    ]

    operations = [
        migrations.AddField(
            model_name='promocion',
            name='filtro_atributo_nombre',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='promocion',
            name='filtro_atributo_valor',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
