# Generated by Django 5.2.1 on 2026-04-24 00:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0015_replace_embedding_with_phash'),
        ('ventas', '0009_add_filtro_atributo_promocion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promocion',
            name='tipo_condicion',
            field=models.CharField(choices=[('categoria', 'Categoría de producto'), ('monto', 'Monto mínimo de compra'), ('monto_categoria', 'Monto mínimo por categoría')], max_length=20),
        ),
        migrations.CreateModel(
            name='Oferta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('descripcion', models.TextField(blank=True)),
                ('activo', models.BooleanField(default=True)),
                ('aplica_a', models.CharField(choices=[('producto', 'Producto específico'), ('categoria', 'Categoría completa')], max_length=20)),
                ('tipo', models.CharField(choices=[('porcentaje', 'Descuento porcentual (%)'), ('fijo', 'Descuento fijo ($)'), ('2x1', '2x1 — lleva 2, paga 1'), ('nxprecio', 'N piezas por $X')], max_length=20)),
                ('valor', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('cantidad_n', models.PositiveIntegerField(blank=True, null=True)),
                ('fecha_inicio', models.DateField(blank=True, null=True)),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ofertas', to='inventario.categoria')),
                ('producto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ofertas', to='inventario.producto')),
            ],
            options={
                'ordering': ['-activo', 'nombre'],
            },
        ),
    ]
