# Generated by Django 5.2.1 on 2026-05-09 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0011_filtros_atributos'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfigTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_empresa', models.CharField(default='COMERCIALIZADORA MODELO', max_length=30)),
                ('telefono', models.CharField(blank=True, default='', max_length=30)),
                ('direccion', models.CharField(blank=True, default='', max_length=30)),
                ('mostrar_id_producto', models.BooleanField(default=True, help_text='Muestra #123 antes del nombre del producto')),
                ('mostrar_tipo_precio', models.BooleanField(default=True, help_text='Muestra la línea "PRECIO MAYOREO APLICADO"')),
                ('texto_mayoreo', models.CharField(default='PRECIO MAYOREO APLICADO', max_length=30)),
                ('texto_menudeo', models.CharField(default='PRECIO MENUDEO APLICADO', max_length=30)),
                ('mensaje_pie', models.CharField(default='NO CAMBIOS NI DEVOLUCIONES', max_length=30)),
                ('mensaje_agradecimiento', models.CharField(default='GRACIAS POR TU COMPRA', max_length=30)),
            ],
            options={
                'verbose_name': 'Configuración de Ticket',
            },
        ),
    ]
