# Generated by Django 5.2.1 on 2026-05-20 06:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda_temp', '0001_initial'),
        ('ventas', '0012_config_ticket'),
    ]

    operations = [
        migrations.CreateModel(
            name='IdempotencyKey',
            fields=[
                ('key', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('operacion', models.CharField(choices=[('venta', 'Venta POS'), ('nuevo_producto', 'Registro de producto')], max_length=32)),
                ('status_code', models.IntegerField(default=200)),
                ('response_json', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('empleado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tienda_temp.empleado')),
            ],
            options={
                'indexes': [models.Index(fields=['-created_at'], name='ventas_idem_created_8eb2fd_idx'), models.Index(fields=['operacion', '-created_at'], name='ventas_idem_operaci_277276_idx')],
            },
        ),
    ]
