# Generated by Django 5.2.1 on 2026-05-20 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0013_idempotencykey'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idempotencykey',
            name='operacion',
            field=models.CharField(choices=[('venta', 'Venta POS'), ('nuevo_producto', 'Registro de producto'), ('agregar_inventario', 'Agregar inventario')], max_length=32),
        ),
    ]
