# Generated by Django 5.2.1 on 2026-05-22 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0014_alter_idempotencykey_operacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='promocion',
            name='atributos_enlazados',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='promocion',
            name='filtros_disparador',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
