# Generated by Django 5.2.1 on 2026-09-21 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0018_remove_producto_foto_thumbnail'),
        ('ventas', '0015_promocion_atributos_enlazados_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='oferta',
            name='productos_combo',
            field=models.ManyToManyField(blank=True, related_name='ofertas_combo', to='inventario.producto'),
        ),
        migrations.AlterField(
            model_name='oferta',
            name='aplica_a',
            field=models.CharField(choices=[('producto', 'Producto específico'), ('categoria', 'Categoría completa'), ('combo', 'Combo de productos específicos')], max_length=20),
        ),
    ]
