# Generated by Django 5.2.1 on 2026-06-14 23:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sucursales', '0001_initial'),
        ('tienda_temp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sucursal',
            name='dueño_servicios',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sucursales_como_responsable_servicios', to='tienda_temp.empleado'),
        ),
    ]
